### ISSUE TITLE
Duplicate Scoreboard Objective on Leave

### ISSUE THREAD

**Issue by aurorasmiles** [Jakllp/war#1]
It seems like https://github.com/Jakllp/war/blob/develop/war/src/main/java/com/tommytony/war/Team.java#L428 sometimes creates duplicate scoreboard objectives, which can cause players to be kicked from the server if it is behind a Bungeecord/Waterfall proxy.
See also https://github.com/PaperMC/Waterfall/issues/318 

```DownstreamBridge <-> [Game] - encountered exception
java.lang.IllegalArgumentException: Objective df_p already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:182) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:67) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
	at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by Jakllp** [comment]
Seems to be an issue with the updateScoreboard() function.
I gotta admit I haven't touched any of the scoreboard things yet so that's gonna be interesting.
Especially because I don't have ANY knowledge about Bungeecord/Waterfall but we'll see.
The issue you linked seems to explain it to a degree which might help me fix it.

Thank you for reporting it though!

**Comment by aurorasmiles** [comment]
From what I've gathered it's nothing really with Bungeecord, it's more of a general client issue. The client does not allow duplicate objective names, which can cause issues. Usually that might be an issue if multiple servers within the same network create the same objective, but in this case it seems to be completely Wars fault. A simple check for existing objectives *might* already be enough, but honestly scoreboards are weird.

**Comment by Jakllp** [comment]
I've read through the linked issue and basically came to the same conclusion.

I'll have to do some testing as I don't even know what the scoreboard is used for (I'm not using it personally) but this seems fixable.
Will get to it soon™

Funnily enough the scoreboard does not seem to work on my test-server

**Comment by Jakllp** [comment]
Issue-Info for myself:
Zone loading sequence seems to be broken
- scoreboard tries to create itself before zonecfg being loaded -> null value -> no scoreboard

**Comment by Jakllp** [comment]
I just noticed that you linked the develop branch, which isn't the actual branch I'm working in (funnily enough).

Scoreboards are still causing problems though.

**Comment by Jakllp** [comment]
Okay I gotta admit I'm confused.
In the newer versions of the plugin (can't speak for the old ones) there is no way that an objective called "df_p" could be registered.
(unless I'm blind)

The only way this could happen is if this line:
`player.setScoreboard(Bukkit.getScoreboardManager().getMainScoreboard());`
Could somehow cause this.

Could you try the [this](https://github.com/Jakllp/war/releases/tag/v2.8.3-pre) version of the plugin and report back if the problem still persists?

**Comment by aurorasmiles** [comment]
I do believe that that log is a bit older. A more current one had `zs_game_score_pl` as a duplicate objective

**Comment by Jakllp** [comment]
Okay this really does not seem like a war issue (at least as long as I'm not completely missing anything - which always can be the case so...)

The plugin has exactly one line of code where a new objective is created:
https://github.com/Jakllp/war/blob/release/2.0.0/src/main/java/com/tommytony/war/Warzone.java#L1230

The objective name is setas `this.getScoreboardType().name()`
This means they can only be:
`NONE`;`POINTS`;`LIFEPOOL`;`TOPKILLS`;`PLAYERCOUNT` or `SWITCHING` (even though I don't know if that works yet)
See https://github.com/Jakllp/war/blob/release/2.0.0/src/main/java/com/tommytony/war/config/ScoreboardType.java


I'm gonna check if the plugin copies objectives somewhere. Just to be sure
Edit: Didn't find that. The plugin resets a players scoreboard to the MainScoreboard of the server. I honestly don't know if that could cause this for some reason

**Comment by aurorasmiles** [comment]
Seems like War is not the issue here, I'm sorry.

**Comment by Jakllp** [comment]
No problem!

Thank you for reporting it anyway as it opened my eyes to the scoreboard-feature of the plugin ^^
